# -*- coding: utf-8 -*-
"""ESCAPE CHARACTER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tsoEhArZol6G4EKUq4gBVousKVwMlTkx
"""

print('Dia berkata: "Pergilah!"')

print(" Aku menimpali : \"Apakah kau ingin aku 'angkat kaki'? \"")

print('\\')

