# -*- coding: utf-8 -*-
"""FORMAT STRING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxLDAjR5Ss4mL7bzWADDmTjvYqoeNhWX

Format Specifiers
"""

template = 'Halo, saya %s dari %s'

print(template % ('Lendis Fabri', 'Indonesia'))
# output: Halo, saya Lendis Fabri dari Indonesia

"""Fungsi Fromat"""

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka makan {} dan minum {}'

print(template. format (nama = 'Lendis Fabri', asal = 'Indonesia') )
# Halo, saya Lendis Fabri dari Indonesia
print(template_2. format('Nasi Goreng', 'air putih'))
# Saya suka makan Nasi Goreng dan minum air putih

"""String Interpolation"""

nama = 'Louis Fabri'
asal = 'Alaska'
print(f'Perkenalkan saya {nama} dari {asal}😎')

"""Memecah String Menjadi List dan Sebaliknya

"""

alamat = 'Surabaya, Jawa Timur, Indonesia'

print(alamat. split (','))

print(alamat. split())

print(alamat. split(', '))

print('❤️'.join(['aku', 'suka', 'python']))
print('🦖' .join(alamat.split(', ')))

"""Upper Case"""

print('halo selamat pagi !'. upper())
print('halo selamat malam !'. upper())

"""Lower"""

print('APA KABAR !'. lower())
print('LAGI DIMANAAAA?'. lower())

"""Tittle Case"""

print('daun tidak pernah membenci angin'. title())
print('LASKAR PELANGI'. title())

"""Reverse Case"""

print('Indonesia Adalah Negara Kepulauan'. swapcase())
print('aKu cInTa NeGeriKu'. swapcase())

"""Mecari Kata Pada String"""

angka = '12345'
print ('Index angka 3:', angka. find ('3'))
print('Index angka 45:', angka. find('45'))
print( 'Index angka 35:', angka. find ('35'))

asal = 'Kanada'
print(asal. find ('d'))

"""Mereplace"""

ibu_kota = 'Jakarta'

print(ibu_kota. replace ('a', 'i'))
print(ibu_kota. replace ('kar', '🦁'))

print(ibu_kota. replace('a', ''))

"""Menghitung Jumlah Karakter"""

paragraf = 'Baru- baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf. count('b')

print(f'Kata"di" muncul sebanyak {x}kali')

paragraf = "Baru- baru ini telah ditemukan sebuah meteor di suatu sungai"
print(paragraf. count('di'))
print(paragraf. count('a'))