# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FLaV89hjt0qvSjop2VgCj8fAmLoKq1cg
"""

nama = ('Claudia Najwa Hidayat')
asal = ("Indonesia")

print(nama)

print(nama)

print(asal)

print(nama,asal)

print(nama+asal)

print("Halo, nama saya")

print("Halo, nama saya", nama, "asal saya dari", asal)

data_lengkap = nama + asal
print(data_lengkap)

"""**STRING + NON STRING**"""

asal_kota = "Bandar Lampung"
kode_pos = 3514

asal_kota_kode_pos = asal_kota + str(kode_pos)
print(asal_kota_kode_pos)

asal_kota_x3 =  asal_kota * 3
print(asal_kota_x3)