# -*- coding: utf-8 -*-
"""Tipe Data Casting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dRrTaP86D-aY0SskSNxO9d2bLzA7cQI8

*   NAMA : CLAUDIA NAJWA HIDAYAT
*   NPM : 2451012013

1.   Memeriksa Jenis Dta
"""

nama = 'Budi'
usia = 20
lajang = True
print (type (nama) )
print (type(usia))
print (type (lajang) )

"""Konversi Tipe Data"""

usia = input( 'Masukkan usia anda:')
print (type(usia))

"""Konversi Data Implisit"""

kata = 'jeruk'*5
print(kata)
print(type(kata))

a = 5/2
print(type(a))

"""Konversi Tipe Data Secara Eksplisit"""

Panjang = input('Masukan Panjang: ')
Lebar = input('Masukan Lebar: ')
print('Luas =', panjang*lebar)

panjang = int(input('Masukan Panjang: '))
lebar = float(input('Masukan Lebar: '))

print('Luas =', panjang * lebar)

"""Konversi Tipe Data Secara Numerik


"""

panjang = int (input ('Masukkan panjang: '))
lebar = float(input ('Masukkan lebar: '))
print ('Luas =', panjang * lebar)

"""KONVERSI NUMERIK KE STRING"""

nama ="Charles"
tahun_lahir = 1950
print(nama + ' lahir ditahun ini ' + str(tahun_lahir))